name: Release Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/template_Build&Test.yml

  release:
    needs: 'build'
    uses: ./.github/workflows/template_Package.yml
    with: 
      tag: ${{ needs.build.outputs.tag }}