name: PR Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/template_Build&Test.yml

  release:
    uses: ./.github/workflows/template_Package.yml
